# Generated by Django 3.2.8 on 2022-09-13 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fpuserdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField()),
                ('id1', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('body', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='RegisteredUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('emailid', models.CharField(max_length=100, unique=True)),
                ('phoneNum', models.CharField(blank=True, max_length=20, null=True)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
    ]
